# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6f74899b00730e82af09775ec4715973c0a5de1e47ba828f86f7bc75ffc0023ff6480bb3ac3fdf259089fc4b73e40d15a78fb13af77ae01ad7eb8784aca8b254

test:
  secret_key_base: 531e2e42d51d67e3d4c8e984106d1d7d0164c517da45859bd843034acc0a4d53e98895a0d9eaa71561c2b1e40972fea1e2238d936faa45d8627c44c12a273c21

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
